### ISSUE TITLE
Window does not close on the Mac untill the process exists

### ISSUE THREAD

**Issue by aviks** [aviks/MiniFB.jl#2]
Which makes it somewhat annoying to develop on the REPL. However, calling a second `mfb_window_open` will clear up the old window and launch the new, so iterative development is still possible. The other option is  to always run from the shell. 

Asked upstream: https://github.com/emoon/minifb/issues/44

**Comment by Darky-Lucera** [comment]
Now the window closes properly using Cocoa and Metal APIs.

Please, try it now and let us know if it works.

**Comment by aviks** [comment]
Fixed upstream. `]up` will fix it in Julia.

Thanks @Darky-Lucera
