### ISSUE TITLE
Does not work on Arch linux with system /usr/lib/libstdc++.so.6.0.30

### ISSUE THREAD

**Issue by feanor12** [aviks/MiniFB.jl#20]
#### Problem 

When I install MiniFB on julia 1.8  (taken the original binary build from the official julia website) I get the following error.

```
julia> mfb_open_ex("My Window", 400, 400, MiniFB.WF_RESIZABLE)
libGL error: MESA-LOADER: failed to open radeonsi: /usr/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error:  BadMatch
  Request Major code 150 (GLX)
  Request Minor code 5 ()
  Error Serial #41
  Current Serial #41
```

#### Workaround

Replacing the symlink in `/usr/lib/julia for libstdc++.so.6` which points to `libstdc++.so.6.0.29` with the system library (`libstdc++.so.6.0.30`) I can get MiniFB to work.

```
cd /usr/lib/julia/
sudo rm libstdc++.so.6 
sudo ln -s /usr/lib/libstdc++.so.6.0.30 libstdc++.so.6
```
#### System
 [cc649173] MiniFB v0.1.1
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 1 on 16 virtual cores

**Comment by aviks** [comment]
These might be relevant: 

* https://github.com/JuliaLang/julia/issues/34276
* https://discourse.julialang.org/t/glibcxx-version-not-found/82209/

**Comment by aviks** [comment]
Those links above suggest that this is an issue with how julia is built and distributed, and there is really nothing we can do about that here. Switching the .so, or loading the OS version with LD_PRELOAD is the only workaround at the moment. Sorry!
