### ISSUE TITLE
Build MiniFB_jll for Linux musl

### ISSUE THREAD

**Issue by jpsamaroo** [aviks/MiniFB.jl#5]
minifb appears to compile perfectly fine on Alpine Linux with or without the CMake `-DUSE_WAYLAND_API=ON` option.

**Comment by aviks** [comment]
Mose fixed the BB build here: https://github.com/JuliaPackaging/Yggdrasil/pull/1665 to support musl. Should work now -- can you try please?

**Comment by jpsamaroo** [comment]
This seems to work, I just need to figure out how to get around https://github.com/JuliaLang/julia/issues/36458. But I'm able to manually call `mfb_open` by using `dlsym` manually, so I'm closing this.
