### ISSUE TITLE
Add helper methods for callback functions

### ISSUE THREAD

**Issue by jebej** [aviks/MiniFB.jl#9]
Would you be interested in having helper methods to set the callback functions which automatically create the function pointer with ` @cfunction` ? Since the signature is fixed by the library we can just assume that the user is passing a valid method.

Eg. we could define:

```julia
function mfb_set_keyboard_callback(window, keyboard::Function)
    keyboard_c = @cfunction(keyboard, Cvoid, (Ptr{Cvoid}, mfb_key, mfb_key_mod, Bool))
    mfb_set_keyboard_callback(window, keyboard_c)
end
```

Let me know if that would be good to have, and if the naming, or something else would need to be changed

**Comment by aviks** [comment]
Yeah, that might be a good idea!

**Comment by jebej** [comment]
Any input on the api? Should I just add methods to the various `mfb_set_*_callback` functions?

**Comment by jebej** [comment]
I had to add `$` to the macro call since the function pointer must be created at runtime. I am not sure whether that's a drawback or not.
